<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.7</Version>
    <ApplicationIcon>Resources\CR34TE-Light-Patch-Builder.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\CR34TE-Light-Patch-Builder.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PDFsharp-WPF" Version="6.2.2" />
  </ItemGroup>
</Project>
